version: '3.8'

services:
  pythonapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./code:/code
    environment:
      - PYTHONUNBUFFERED=1
    command: python main.py